### ISSUE TITLE
admin/header.php

### ISSUE THREAD

**Issue by DySyre** [f9ki3/danielle_motors#7]
Trina try ko i import ung water css pero paano ba sya isama along bootstrap link rel?

ito kasi nagiging itsura pag parehas inimport
![image](https://github.com/f9ki3/danielle_motors/assets/119650160/c4b674c6-a71a-4137-ad39-608b718bbeaa)

ito naman nagiging itsura pag kinomment ung link ng bootstrap pag tinanggal
![image](https://github.com/f9ki3/danielle_motors/assets/119650160/a5f16826-7d75-4cbb-a4cf-3a568ccf61fb)

**Comment by f9ki3** [comment]
haha outdated
